stages:
  - test
  - mirror

variables:
  GIT_DEPTH: "0"            # on veut l'historique complet pour un push --mirror

mirror_to_github:
  stage: mirror
  image: alpine:3.20
  variables:
    GIT_DEPTH: "0"
    GIT_STRATEGY: fetch
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - apk add --no-cache git
    - git config --global user.email "${GITLAB_USER_EMAIL:-ci@gitlab}"
    - git config --global user.name  "${GITLAB_USER_NAME:-gitlab-ci}"
    # Récupère toutes les refs (branches, tags, notes)
    - git fetch --prune --tags origin '+refs/heads/*:refs/remotes/origin/*' '+refs/notes/*:refs/notes/*'
    # Matérialise les branches locales depuis origin/* (évite la suppression côté GitHub)
    - |
      set -e
      git for-each-ref --format='%(refname:strip=3)' refs/remotes/origin \
      | grep -v '^HEAD$' \
      | while read -r b; do
          git branch -f "$b" "origin/$b"
        done
  script:
    - git remote remove mirror 2>/dev/null || true
    - git remote add mirror "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git"
    - git push --mirror mirror

